name: Support Request
description: File a support request
title: "[SUPPORT]: "
labels: ["support"]
body:
  - type: markdown
    attributes:
      value: |
        You are currently submitting a support request.
        If you experiencing any bugs, please create a bug report [here](https://github.com/jkampich1411/jkampich1411/issues/new)!
  - type: dropdown
    id: type-of-support
    attributes:
      label: Why are you creating this request?
      description: Are you having a question or is something on your mind that you want us to know?
      options:
        - Generic Support Request
        - Question
        - Feedback
      validations:
        required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: duplicate
    attributes:
      label: Have you checked if this request is duplicate?
      description: Did you check among other issues if it is duplicate?
      options:
        - label: I have checked among other issues.
          required: true
