name: Support Request
description: File a support request
title: "[SUPPORT]: "
labels: ["support"]
body:
  - type: markdown
    attributes:
      value: |
        ## You are currently submitting a support request.
        If you experiencing any critical bugs, which require immediate action, please create a bug report [here](https://github.com/jkampich1411/jkampich1411/issues/new/choose)!
  - type: markdown
    attributes:
      value: |
        ## A bot called @jkdev-github-bot will be replying to your issue after creation. Please respond to any questions it has! Thank you!
  - type: dropdown
    id: type-of-support
    attributes:
      label: Why are you creating this request?
      description: Are you having a question or are you experiencing a bug?
      options:
        - Question about Software
        - Bug Report
    validations:
      required: true
  - type: dropdown
    id: what-software-support
    attributes:
      label: What software needs support?
      description: For what software do you want to file a support request?
      options:
        - VSCode Extension
        - Statuspage
        - Something else
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? / What is your Question?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what is up!
      value: ""
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: vX.X.X
      value: ""
    validations:
      required: true
  - type: input
    id: system
    attributes:
      label: What system version are you using?
      description: 'Please copy/paste the output of "uname -a" (or "winver") here!'
      multiple: true
      placeholder: uname -a / winver
  - type: checkboxes
    id: duplicate
    attributes:
      label: Have you checked if this request is duplicate?
      description: Did you check among other issues if it is duplicate?
      options:
        - label: I have checked among other issues.
          required: true
